### ISSUE TITLE
Can't @apply styles

### ISSUE THREAD

**Issue by CapsE** [buz-zard/tailwind-bootstrap-grid#24]
Hi, is there a reason why I can't @apply the classes generated by this plugin? 

`.cool-class-which-is-also-a-col {
@apply col-6 
}`

This will not throw an error but also not apply any styles to the class.

**Comment by buz-zard** [comment]
Hmm, that's odd... I tried:

```css
.whatever-col {
  @apply col;
  background: green;
}

.whatever-col-auto {
  @apply col-auto;
  background: green;
}

.whatever-col-1 {
  @apply col-1;
  background: red;
}
```

Which outputted:

```css
.whatever-col {
  flex-basis: 0;
  flex-grow: 1;
  max-width: 100%;
  background: green;
}

.whatever-col-auto {
  flex: 0 0 auto;
  width: auto;
  max-width: 100%;
  background: green;
}

.whatever-col-1 {
  flex: 0 0 33.333333333333336%;
  max-width: 33.333333333333336%;
  background: red;
}
```

Though I noticed that `container` can't be applied since it is created as a component not an utility:

```css
.whatever-container {
  @apply container;
  background: red;
}
```

Could you provide the options that you pass to the config? Because with defaults I get output of:

```css
.cool-class-which-is-also-a-col {
  flex: 0 0 50%;
  max-width: 50%;
}
```
