### ISSUE TITLE
Full custom prefix support

### ISSUE THREAD

**Issue by buz-zard** [buz-zard/tailwind-bootstrap-grid#5]
With following options:
```js
  options: {
    prefix: '✅-',
    separator: '_🚧_',
  },
```

The following css gets generated:
```css
.✅-row.✅-no-gutters {
  margin-right: 0;
  margin-left: 0;
}

.✅-row.✅-no-gutters > .✅-col,
.✅-row.✅-no-gutters > .✅-mobile_🚧_col,
.✅-row.✅-no-gutters > .✅-tablet_🚧_col,
.✅-row.✅-no-gutters > .✅-desktop_🚧_col,
.✅-row.✅-no-gutters > [class*="col-"],
.✅-row.✅-no-gutters > [class*="mobile_🚧_col-"],
.✅-row.✅-no-gutters > [class*="tablet_🚧_col-"],
.✅-row.✅-no-gutters > [class*="desktop_🚧_col-"] {
  padding-right: 0;
  padding-left: 0;
}
```

While this is the expected output
```css
.✅-row.✅-no-gutters {
  margin-right: 0;
  margin-left: 0;
}

.✅-row.✅-no-gutters > .✅-col,
.✅-row.✅-no-gutters > .mobile_🚧_✅-col,
.✅-row.✅-no-gutters > .tablet_🚧_✅-col,
.✅-row.✅-no-gutters > .desktop_🚧_✅-col,
.✅-row.✅-no-gutters > [class*="✅-col-"],
.✅-row.✅-no-gutters > [class*="mobile_🚧_✅-col-"],
.✅-row.✅-no-gutters > [class*="tablet_🚧_✅-col-"],
.✅-row.✅-no-gutters > [class*="desktop_🚧_✅-col-"] {
  padding-right: 0;
  padding-left: 0;
}
```
